### ISSUE TITLE
Week3 Communication

### ISSUE THREAD

**Issue by DavyGuo** [UBC-MDS/DSCI_522_Forest_Fire_Analysis#16]
@jpush1773 

There are a few things:

1. As we discussed together, I finished the Makefile and push to my forked repo, please kindly review and let me know your feedback. However, I did run into troubles when test the makefile (to be specific, the last rendering part is a disaster), to make it work, I had to make a change to the report.Rmd file - changing the "here::here" statement. Please let me know if this is ok. 

2. About our repo structure, I feel like there are some "redundancy", for example, each repo has a readme file which is blank, do you think we can delete them? Also, the "script_ex.png" under the img repo, and the "forest.R" file under script repo is used for proposal. Since we've moved over proposal phase, should we delete this two as well?

We'll discuss this and update the "Repository Structure" part in the main repo README file.

**Comment by jpush1773** [comment]
1. That's unfortunate. It seems "here::here" is problematic and not well understood. A good learning experience. I would like to know what other rendering issues we are having. We will need to iterate the report and keep problem solving so that the rendering is flawless.
2. I noticed that each repo has an individual readme. Also,  I'm not sure what to do with our proposal work other than move it off of the repo and store it in the forked repo. 
3. Let's connect early this week to review the script issue. When I reviewed your copy, it looked consistent with class notes.  We will also need to consider using Docker for this week.
4. The file structure in the readme is good. It adds clarity for someone new to the repo.
